alias zshconfig="vim ~/.zshrc"
#alias vncserver='x11vnc -rfbauth .x11vnc/passwd'
alias vncserver='x11vnc -display :0 -many -rfbauth ~/.x11vnc/passwd'
alias youtube-dl-mp3='youtube-dl --extract-audio --add-metadata --audio-format mp3'
alias cls='clear'
alias diffmeld='meld'
alias rm='rm -i'
alias ntpsync='sudo ntpdate ntp.ubuntu.com'
alias gdrive='grive'
